name: radonpy
channels:
  - conda-forge
dependencies:
  - python>=3.9
  - rdkit>=2020.03
  - mdtraj>=1.9
  - matplotlib
  - pint>0.24
  - ipykernel
  - numpy
  - pandas
  - scipy
  - psi4
  - dftd3-python
  - resp
  - pip:
    - git+https://github.com/jaclark5/minepy@update_install
    - -e .