[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "radonpy-pypi"
dynamic = ["version"]
description = "RadonPy is a Python library to automate physical property calculations for polymer informatics."
readme = "README.md"
license = "BSD-3-Clause"
requires-python = ">=3.7"
authors = [
    {name = "Yoshihiro Hayashi", email = "yhayashi@ism.ac.jp"}
]
keywords = ["polymer informatics", "molecular dynamics"]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Topic :: Scientific/Engineering :: Chemistry",
    "Topic :: Scientific/Engineering :: Physics",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
dependencies = [
    "numpy",
    "pandas",
    "scipy",
    "psutil",
    "matplotlib",
    "rdkit>=2020.03",
    "mdtraj>=1.9",
]

[project.optional-dependencies]
lammps = [
    "lammps>=2020.03.03",
]
biopolymers = [
    "ambertools",
    "intermol",
]
minepy = [
    "minepy",
]

[project.urls]
Homepage = "https://github.com/RadonPy/RadonPy"
Repository = "https://github.com/RadonPy/RadonPy"

[tool.setuptools]
platforms = ["Linux", "Mac OS-X", "Unix", "Windows"]

[tool.setuptools.packages.find]
include = ["radonpy*"]

[tool.setuptools.package-data]
radonpy = [
    "ff/ff_dat/*.json",
    "core/pdb/*.pdb"
]

[tool.setuptools.dynamic]
version = {attr = "radonpy.__version__"}
